[colors]

ansi = ["#101010", "#ff7676", "#a3d6a3", "#ffffff", "#b3b3b3", "#f4b8e4", "#fafafa", "#a5adce"]
brights = ["#666666", "#ff5733", "#86cd82", "#d9ba73", "#ffffff", "#f2a4db", "#5abfb5", "#b5bfe2"]

foreground = "#ffffff"
background = "#101010"
cursor_bg = "#b0b0b0"
cursor_fg = "#101010"
cursor_border = "#b0b0b0"
selection_bg = "#272727"
selection_fg = "#b0b0b0"
split = "#ffffff"
compose_cursor = "#d9ba73"
scrollbar_thumb = "#b0b0b0"

[colors.tab_bar]
inactive_tab_edge = "#272727"
background = "#272727"

[colors.tab_bar.active_tab]
fg_color = "#ffffff"
bg_color = "#101010"

[colors.tab_bar.inactive_tab]
fg_color = "#777777"
bg_color = "#272727"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#000000"
bg_color = "#ebebeb"

[colors.tab_bar.new_tab]
fg_color = "#b0b0b0"
bg_color = "#272727"

[colors.tab_bar.new_tab_hover]
fg_color = "#000000"
bg_color = "#ebebeb"
intensity = "Bold"

[metadata]
aliases = []
name = "koda-dark"
